stages:
  data_ingestion:
    cmd: python  src/data_ingestion.py
    deps: 
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing.py:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interm
  feature_engineering.py:
    cmd: python src/feature_engineering.py
    deps:
    - data/interm
    - src/feature_engineering.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics :
    - reports/metrics.json

